#!/usr/bin/env python3
"""Digère les transcripts Claude Code en un digest JSON compact pour l'audit hebdo.

Les transcripts brut font ~350 Mo/semaine : illisibles en contexte. Ce script en
extrait le signal (prompts réels, outils, erreurs, friction, coût) en ~60 Ko.

Usage:
    python extract_usage.py [--days 7] [--out digest.json] [--scope all|pro|perso]
"""
import argparse
import glob
import json
import os
import re
import sys
import time
from collections import Counter, defaultdict

PROJECTS_DIR = os.path.expanduser("~/.claude/projects")

# Blocs injectés par le harness : on les retire du prompt sans jeter le prompt
# lui-même (un vrai message de l'utilisateur peut avoir un system-reminder collé à la fin).
NOISE_BLOCKS = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S),
    re.compile(r"<local-command-caveat>.*?</local-command-caveat>", re.S),
    re.compile(r"<command-(name|message|args)>.*?</command-\1>", re.S),
    re.compile(r"Caveat: The messages below were generated by the user[^\n]*"),
    re.compile(r"Shell cwd was reset[^\n]*"),
]

# Marqueurs de friction : l'utilisateur corrige, annule, ou répète une consigne.
FRICTION_PATTERNS = [
    (r"^\s*(non|nan|no)\b", "négation directe"),
    (r"\bpas (comme ça|ce que|du tout|ça)\b", "pas ce qui était demandé"),
    (r"\bje t'?ai (dit|demandé|précisé)\b", "consigne répétée"),
    (r"\bje te l'?ai (dit|déjà dit)\b", "consigne répétée"),
    (r"\b(combien de fois|encore une fois|comme la dernière fois)\b", "consigne répétée"),
    (r"\b(annule|revert|rollback|oublie ça)\b", "annulation"),
    (r"\b(arrête|attends|stop)\b", "interruption verbale"),
    (r"\btu (as|a) (oublié|raté|cassé|zappé)\b", "oubli"),
    (r"\bt'?as (oublié|raté|cassé)\b", "oubli"),
    (r"\b(relis|recommence|reprends)\b", "reprise"),
    (r"\b(c'?est faux|c'?est pas ça|faux\b)", "résultat incorrect"),
    (r"\b((ça|ca|cela) (ne )?marche pas|ne fonctionne pas|toujours pas)\b", "ne marche pas"),
    (r"\bpourquoi tu (as|n'?as)\b", "incompréhension du comportement"),
    (r"\b(je (ne )?veux pas|ne fais pas|il ne faut pas)\b", "interdiction"),
    (r"\bjamais (de|plus|ça|faire|mettre|toucher|commit|push)\b", "interdiction forte"),
    (r"\bne .{0,20} jamais\b", "interdiction forte"),
    (r"\b(fais|mets) plutôt\b", "réorientation"),
    (r"^\s*en fait\b", "réorientation"),
]
FRICTION_RE = [(re.compile(p, re.I), label) for p, label in FRICTION_PATTERNS]

PRO_HINT = re.compile(r"<YOUR_WORK_ORG>", re.I)

# Une skill lancée en slash command arrive comme un prompt utilisateur préfixé par le
# chemin de la skill. Sans ça, `skills_invoked` ne voit que l'outil Skill et sous-compte
# massivement l'usage réel (constat de l'audit du 2026-07-31).
SKILL_EXPANSION_RE = re.compile(r"^Base directory for this skill:\s*(\S.*?)\s*$", re.M)

# Entrées qui ne sont pas des prompts tapés par l'utilisateur : déclenchements de tâches
# planifiées, retours de tâches de fond, sorties de commandes locales.
HARNESS_KINDS = (
    ("<scheduled-task", "déclenchement de tâche planifiée"),
    ("<task-notification", "notification de tâche de fond"),
    ("<local-command-stdout", "sortie de commande locale"),
)


def project_name(path):
    """Nom lisible du projet à partir du répertoire encodé de ~/.claude/projects."""
    raw = os.path.basename(os.path.dirname(path))
    name = raw.replace("<USER_PROJECT_PREFIX>", "")
    name = name.replace("<TEMP_PREFIX>", "tmp/")
    name = name.replace("<USER_PREFIX>", "")
    return name.replace("-", "/") if name else raw


def text_of(content):
    """Aplatit un message.content (str ou liste de blocs) en texte brut."""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    out = []
    for b in content:
        if isinstance(b, dict) and b.get("type") == "text":
            out.append(b.get("text") or "")
    return "\n".join(out)


def strip_noise(txt):
    """Retire les blocs du harness et renvoie ce que l'utilisateur a réellement écrit."""
    for rx in NOISE_BLOCKS:
        txt = rx.sub("", txt)
    return txt.strip()


def friction_labels(txt):
    """Labels de friction déclenchés par ce prompt (heuristique, pas une vérité)."""
    head = txt[:400]
    return sorted({label for rx, label in FRICTION_RE if rx.search(head)})


def slash_command(raw):
    m = re.search(r"<command-name>\s*([^<]+?)\s*</command-name>", raw)
    return m.group(1).strip() if m else None


def skill_expansion(txt):
    """Nom de la skill si ce prompt est l'expansion d'une skill, sinon None."""
    m = SKILL_EXPANSION_RE.search(txt)
    if not m:
        return None
    return os.path.basename(m.group(1).rstrip("\\/")) or None


def harness_kind(txt):
    """Catégorie d'entrée harness, ou None si c'est un prompt tapé par l'utilisateur."""
    head = txt.lstrip()[:40]
    for marker, label in HARNESS_KINDS:
        if head.startswith(marker):
            return label
    return None


def scan_session(path, cutoff):
    """Extrait les métriques et le signal textuel d'un transcript."""
    s = {
        "session": os.path.basename(path)[:8],
        "project": project_name(path),
        "start": None,
        "end": None,
        "title": None,
        "prompts": [],
        "tools": Counter(),
        "tool_errors": Counter(),
        "error_samples": [],
        "interruptions": 0,
        "denials": 0,
        "denial_samples": [],
        "skills": Counter(),
        "harness": Counter(),
        "slash": Counter(),
        "subagents": Counter(),
        "models": Counter(),
        "assistant_turns": 0,
        "tokens": Counter(),
        "sidechain_turns": 0,
        "compactions": 0,
        "in_window": False,
    }
    pending = {}  # tool_use_id -> nom d'outil, pour rattacher les erreurs

    try:
        fh = open(path, encoding="utf-8", errors="replace")
    except OSError:
        return None

    with fh:
        for line in fh:
            try:
                d = json.loads(line)
            except (ValueError, TypeError):
                continue

            ts = d.get("timestamp")
            if ts:
                if ts < cutoff:
                    continue  # activité antérieure à la fenêtre : ignorée
                s["in_window"] = True
                if s["start"] is None or ts < s["start"]:
                    s["start"] = ts
                if s["end"] is None or ts > s["end"]:
                    s["end"] = ts

            typ = d.get("type")

            if typ == "ai-title" and not s["title"]:
                s["title"] = (d.get("aiTitle") or "")[:120]
                continue

            msg = d.get("message") or {}
            content = msg.get("content")

            if typ == "assistant":
                if d.get("isSidechain"):
                    s["sidechain_turns"] += 1
                s["assistant_turns"] += 1
                if msg.get("model"):
                    s["models"][msg["model"]] += 1
                u = msg.get("usage") or {}
                for k in ("input_tokens", "output_tokens", "cache_read_input_tokens",
                          "cache_creation_input_tokens"):
                    if isinstance(u.get(k), int):
                        s["tokens"][k] += u[k]
                if isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_use":
                            name = b.get("name") or "?"
                            s["tools"][name] += 1
                            pending[b.get("id")] = name
                            inp = b.get("input") or {}
                            if name == "Skill" and isinstance(inp.get("skill"), str):
                                s["skills"][inp["skill"]] += 1
                            elif name == "Agent" and isinstance(inp.get("subagent_type"), str):
                                s["subagents"][inp["subagent_type"]] += 1
                continue

            if typ != "user":
                if typ == "system" and "compact" in json.dumps(d).lower():
                    s["compactions"] += 1
                continue

            # --- côté user : soit un résultat d'outil, soit un vrai prompt ---
            if d.get("toolUseResult") is not None:
                tr = d.get("toolUseResult")
                blob = tr if isinstance(tr, dict) else {}
                errored = bool(blob.get("is_error"))
                tool = "?"
                if isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_result":
                            tool = pending.get(b.get("tool_use_id"), "?")
                            if b.get("is_error"):
                                errored = True
                if errored:
                    s["tool_errors"][tool] += 1
                    if len(s["error_samples"]) < 5:
                        s["error_samples"].append(
                            {"tool": tool, "excerpt": json.dumps(tr)[:200]}
                        )
                continue

            raw = text_of(content)
            if not raw.strip():
                continue

            if "[Request interrupted by user" in raw:
                s["interruptions"] += 1
                continue
            if "doesn't want to proceed" in raw or "tool uses were rejected" in raw:
                s["denials"] += 1
                if len(s["denial_samples"]) < 3:
                    s["denial_samples"].append(raw[:180])
                continue

            cmd = slash_command(raw)
            if cmd:
                s["slash"][cmd] += 1

            txt = strip_noise(raw)
            if len(txt) < 2:
                continue

            # Une expansion de skill est une invocation réelle, pas un prompt tapé.
            sk = skill_expansion(txt)
            if sk:
                s["skills"][sk] += 1
                s["harness"]["expansion de skill"] += 1
                continue

            hk = harness_kind(txt)
            if hk:
                s["harness"][hk] += 1
                continue
            s["prompts"].append({
                "ts": ts,
                "len": len(txt),
                "friction": friction_labels(txt),
                "slash": cmd,
                "text": txt[:260],
            })

    # Une session compte dès qu'elle a de l'activité dans la fenêtre : les sessions
    # longues ou reprises sont précisément celles qui portent le plus de signal.
    if not s["in_window"]:
        return None
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--out", default="usage_digest.json")
    ap.add_argument("--scope", choices=["all", "pro", "perso"], default="all")
    ap.add_argument("--max-prompts", type=int, default=400,
                    help="plafond de prompts inclus dans le digest")
    args = ap.parse_args()

    now = time.time()
    mtime_cutoff = now - args.days * 86400
    # Cutoff ISO large : on filtre finement sur le timestamp de début de session.
    iso_cutoff = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(mtime_cutoff))

    files = [
        f for f in glob.glob(os.path.join(PROJECTS_DIR, "**", "*.jsonl"), recursive=True)
        if os.path.getmtime(f) >= mtime_cutoff
    ]

    sessions = []
    for f in files:
        s = scan_session(f, iso_cutoff)
        if s is None:
            continue
        is_pro = bool(PRO_HINT.search(s["project"]))
        if args.scope == "pro" and not is_pro:
            continue
        if args.scope == "perso" and is_pro:
            continue
        sessions.append(s)

    # --- agrégats ---
    tools = Counter()
    tool_errors = Counter()
    skills = Counter()
    slash = Counter()
    subagents = Counter()
    models = Counter()
    tokens = Counter()
    harness = Counter()
    by_project = defaultdict(lambda: Counter())
    friction_kinds = Counter()
    friction_prompts = []
    error_samples = []
    denial_samples = []

    for s in sessions:
        tools.update(s["tools"])
        tool_errors.update(s["tool_errors"])
        skills.update(s["skills"])
        slash.update(s["slash"])
        subagents.update(s["subagents"])
        models.update(s["models"])
        tokens.update(s["tokens"])
        harness.update(s["harness"])
        p = by_project[s["project"]]
        p["sessions"] += 1
        p["prompts"] += len(s["prompts"])
        p["tool_calls"] += sum(s["tools"].values())
        p["tool_errors"] += sum(s["tool_errors"].values())
        p["interruptions"] += s["interruptions"]
        p["denials"] += s["denials"]
        p["output_tokens"] += s["tokens"].get("output_tokens", 0)
        error_samples.extend(s["error_samples"])
        denial_samples.extend({"project": s["project"], "excerpt": e} for e in s["denial_samples"])
        for pr in s["prompts"]:
            if pr["friction"]:
                friction_kinds.update(pr["friction"])
                friction_prompts.append({
                    "project": s["project"],
                    "ts": pr["ts"],
                    "kinds": pr["friction"],
                    "text": pr["text"],
                })

    # Échantillon de prompts : tous ceux avec friction (signal max), le premier de
    # chaque session (intention), puis un échantillon régulier du reste.
    first_prompts = []
    rest = []
    for s in sessions:
        for i, pr in enumerate(s["prompts"]):
            item = {"project": s["project"], "ts": pr["ts"], "text": pr["text"],
                    "friction": pr["friction"]}
            if i == 0:
                first_prompts.append(item)
            elif not pr["friction"]:
                rest.append(item)
    budget = max(0, args.max_prompts - len(friction_prompts) - len(first_prompts))
    if budget and rest:
        step = max(1, len(rest) // budget)
        sample = rest[::step][:budget]
    else:
        sample = []

    sessions_sorted = sorted(sessions, key=lambda s: s["start"] or "")
    total_prompts = sum(len(s["prompts"]) for s in sessions)
    total_calls = sum(tools.values())
    total_errors = sum(tool_errors.values())

    digest = {
        "period": {
            "days": args.days,
            "generated_at": time.strftime("%Y-%m-%d %H:%M"),
            "scope": args.scope,
            "from": sessions_sorted[0]["start"] if sessions_sorted else None,
            "to": sessions_sorted[-1]["end"] if sessions_sorted else None,
        },
        "totals": {
            "sessions": len(sessions),
            # `prompts` = uniquement ce que l'utilisateur a tapé. Les entrées harness sont
            # comptées à part : les mélanger fausse tous les ratios (cf. audit 2026-07-31).
            "prompts_tapes": total_prompts,
            "prompts": total_prompts,
            "entrees_harness": dict(harness),
            "entrees_harness_total": sum(harness.values()),
            "assistant_turns": sum(s["assistant_turns"] for s in sessions),
            "tool_calls": total_calls,
            "tool_errors": total_errors,
            "tool_error_rate": round(total_errors / total_calls, 4) if total_calls else 0,
            "interruptions": sum(s["interruptions"] for s in sessions),
            "denials": sum(s["denials"] for s in sessions),
            "compactions": sum(s["compactions"] for s in sessions),
            "sidechain_turns": sum(s["sidechain_turns"] for s in sessions),
            "prompts_with_friction": len(friction_prompts),
            "friction_rate": round(len(friction_prompts) / total_prompts, 4) if total_prompts else 0,
            "tokens": dict(tokens),
            "models": dict(models),
        },
        "by_project": [
            {"project": k, **dict(v)}
            for k, v in sorted(by_project.items(), key=lambda kv: -kv[1]["tool_calls"])
        ],
        "tools": [
            {"name": n, "calls": c, "errors": tool_errors.get(n, 0),
             "error_rate": round(tool_errors.get(n, 0) / c, 3) if c else 0}
            for n, c in tools.most_common(30)
        ],
        "skills_invoked": dict(skills.most_common()),
        "slash_commands": dict(slash.most_common()),
        "subagents_used": dict(subagents.most_common()),
        "friction": {
            "by_kind": dict(friction_kinds.most_common()),
            "prompts": friction_prompts[:120],
            "denials": denial_samples[:25],
            "tool_error_samples": error_samples[:25],
        },
        "sessions": [
            {
                "session": s["session"], "project": s["project"],
                "start": s["start"], "end": s["end"], "title": s["title"],
                "prompts": len(s["prompts"]),
                "turns": s["assistant_turns"],
                "tool_calls": sum(s["tools"].values()),
                "tool_errors": sum(s["tool_errors"].values()),
                "interruptions": s["interruptions"],
                "denials": s["denials"],
                "output_tokens": s["tokens"].get("output_tokens", 0),
                "top_tools": dict(s["tools"].most_common(5)),
                "first_prompt": s["prompts"][0]["text"][:200] if s["prompts"] else None,
            }
            for s in sessions_sorted
        ],
        "prompts_first_of_session": first_prompts,
        "prompts_sample": sample,
    }

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(digest, fh, ensure_ascii=False, indent=1)

    size = os.path.getsize(args.out) / 1024
    t = digest["totals"]
    sys.stdout.reconfigure(encoding="utf-8")
    print(f"Digest -> {args.out} ({size:.0f} Ko)")
    print(f"{t['sessions']} sessions | {t['prompts_tapes']} prompts tapés "
          f"(+{t['entrees_harness_total']} entrées harness) | {t['tool_calls']} appels outil")
    print(f"erreurs outil {t['tool_errors']} ({t['tool_error_rate']:.1%}) | "
          f"interruptions {t['interruptions']} | refus {t['denials']}")
    print(f"friction {t['prompts_with_friction']} prompts ({t['friction_rate']:.1%})")


if __name__ == "__main__":
    main()
